POST HTTP://LOCALHOST:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hYyIsImlkIjoiNjU1ZTE1Y2VlYTUzNjc3OTYzNTk5ZjQ2IiwiaWF0IjoxNzAyNzYyMDU3LCJleHAiOjE3MDI3NjU2NTd9.-wuf9YJ0PMJbm9v9eFeYFox59m3BBKB5yIRz_e6qxJY

{
    "comments": ["This blog is dogshit!!!!!1",
      "This blog is the B0MB!",
      "Yeah, this blog rules!"],
    "title": "Auervaara was right",
    "author": "Sr. Pippin",
    "url": "ululululuuu",
    "likes": 2
}