POST HTTP://LOCALHOST:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hYyIsImlkIjoiNjU1ZTE1Y2VlYTUzNjc3OTYzNTk5ZjQ2IiwiaWF0IjoxNzAwODQwOTE1LCJleHAiOjE3MDA4NDQ1MTV9.QSdrmRrvkGjpcjvB1bEZrTMxEbl99pV0viAGZc2T8SI

{
  "title": "Fiftieth blog",
  "author": "Someone who is cat",
  "url": "localhost:3001"
}